on:
  push:
    branches:
      - gh-pages
 
jobs:
  webhook:
    name: Webhook
    runs-on: ubuntu-22.04
    environment: webhooks
    steps:
    - uses: actions/checkout@v2
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          raw-data: Embed.json
