on:
  push:
    branches:
      - main
 
jobs:
  webhook:
    name: Webhook
    runs-on: ubuntu-18.04
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_type: 'json-extended'
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        data: '{ "weapon": "hammer", "drink" : "beer" }'
