on:
  push:
    branches:
      - main
 
jobs:
  webhook:
    name: Webhook
    runs-on: ubuntu-22.04
    environment: webhooks
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        content: "Test"
