on:
  push:
    branches:
      - main
 
jobs:
  webhook:
    name: Webhook
    runs-on: ubuntu-22.04
    environment: webhooks
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
